### ISSUE TITLE
why didn't  xmax and ymax subtract 1

### ISSUE THREAD

**Issue by XCRobert** [adityaarun1/Detectron.pytorch#1]
https://github.com/adityaarun1/Detectron.pytorch/blob/f0842e1decae9ded29c4c54a19846f0cdde022d8/tools/pascal_voc_xml2coco_json_converter.py#L108
The ground truth boxes of pascal voc dataset are 1-based pixel coordinates, maybe you need to modify your codes as below to make it 0-based 
`
int(bndbox.find('xmin').text) - 1,
int(bndbox.find('xmax').text) - 1,
int(bndbox.find('ymin').text) - 1,
int(bndbox.find('ymax').text) - 1
`

**Comment by adityaarun1** [comment]
Ah! nice catch. Thanks a ton for reporting it. 👍
