### ISSUE TITLE
ImportError using Pytorch 1.1.0

### ISSUE THREAD

**Issue by nQuant** [adityaarun1/Detectron.pytorch#10]
Import Error using Pytorch 1.1.0

I encountered this error during a dataset conversion to COCO json format

```
----> 6 from lib.utils.boxes import xyxy_to_xywh
.
.
.
/content/Detectron.pytorch/lib/nn/parallel/scatter_gather.py in <module>()
      6 from ._functions import Scatter, Gather
      7 from torch._six import string_classes, int_classes
----> 8 from torch.utils.data.dataloader import numpy_type_map
      9 
     10 

ImportError: cannot import name 'numpy_type_map'
```

It seems that _numpy_type_map_ has been moved to torch/utils/data/_utils/collate.py in pytorch 1.1.0

Maybe _numpy_type_map_ should be redefined entirely instead of being imported.

EDIT: Same error encountered when executing
> python tools/download_imagenet_weights.py

**Comment by adityaarun1** [comment]
Thanks for reporting this. Can you check again? I hope this quick and dirty fix resolves this issue. If not, feel free to open this issue again.
