### ISSUE TITLE
from torch.utils.data.dataloader import numpy_type_map ImportError: cannot import name 'numpy_type_map'

### ISSUE THREAD

**Issue by engineer1109** [adityaarun1/Detectron.pytorch#2]
from torch.utils.data.dataloader import numpy_type_map
ImportError: cannot import name 'numpy_type_map'

what is it happened?

**Comment by adityaarun1** [comment]
Can you provide me with a little more info? Can you post the command that you fired and the entire output?

**Comment by jcliu0428** [comment]
@engineer1109  
Hi,I just met the same issue.
You can try to install the latest version torch just by:
pip/pip3 install torch
Then you can get torch-nightly(1.0.1),Then the problem will be fixed.
Good luck.

**Comment by adityaarun1** [comment]
Since there seems to be a solution to this problem, I am closing this issue.
