### ISSUE TITLE
torch 1.0.1 not matched torchvision 0.3.0

### ISSUE THREAD

**Issue by unanan** [adityaarun1/Detectron.pytorch#8]
I installed torchvision 0.3.0 first, and it told me:
```
ERROR: torchvision 0.3.0 has requirement torch>=1.1.0, but you'll have torch 1.0.1 which is incompatible.
```
when I ```pip install torch-1.0.1-cp35-cp35m-manylinux1_x86_64.whl```. So what are the matched versions?

**Comment by adityaarun1** [comment]
Can you check with pytorch version `1.1.0`+?
